name: Release

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Test scenario tags'
        required: true
        type: string
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rename
        run: |
          sudo apt-get install rename
      - name: Set up Node.js  # Nodejs版本
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install and Build 
        run: |
          npm install
          npm run compile -- --platform obsidian --distDir dist/obsidian
      - name: Pack
        run: |
          mkdir dist/themes
          cp -r dist/obsidian/dark/* dist/themes/
          cp -r dist/obsidian/light/* dist/themes/
          cd dist/themes/
          rename 's/obsidian-/mweb-/' *
          zip -r themes.zip ./
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/themes/themes.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}