name: Release

on: 
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Test scenario tags'
        required: true
        type: string
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install rename
        run: |
          sudo apt-get install rename
      - name: Set up Node.js  # Nodejs版本
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install and Build 
        run: |
          npm install
          npm run compile -- --platform obsidian --distDir dist/obsidian
      - name: Pack
        run: |
          ./build.sh
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          gh release create "$tag" \
            --title="$tag" \
            --draft dist/assets.zip